# username/repository
id: bachirc/Drop-Everything-v3-web
# name of the software
name: Drop Everything
# current version of the software
version: 1.0.0-beta
# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT
# extension of the favicon, blank to disable
favicon: png

# download button
# if download.popup is true, the download button will open a popup with several download options
# otherwise it will simply open download.url and other options are ignored
# if download.popup is true, any option is optional
# download.cdn.img is optional
# download:
#   popup: true
#   url: https://github.com/mistic100/dev3-documentation/archive/gh-pages.zip
#   bower: jekyll-bootstrap-doc
#   npm: jekyll-bootstrap-doc
#   cdn:
#     url: https://cdnjs.com/libraries/jekyll-bootstrap-doc
#     img: https://alemangui.github.io/pizzicato/img/cdnjs.svg
#     name: cdnjs

# set this to true to replace the generated header navbar by _includes/navbar.html
customNavBar: false

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/BachirC/Drop-Everything-v3

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/BachirC/Drop-Everything-v3
  - title: Issues
    url: https://github.com/BachirC/Drop-Everything-v3/issues?state=open

# header
header:
  color1: "#00293C"
  color2: "#1E656D"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: BachirC
  repo: Drop-Everything-v3

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

livereload: true
reload_port: 5678
